### ISSUE TITLE
Много лишнего и нет картинок/списка

### ISSUE THREAD

**Issue by slaFFik** [mihailShumilov/readability#4]
http://cosydale.com/novyiy-premium-buddypress-shablon-onecommunity.html

**Comment by mihailShumilov** [comment]
как можно больше вычищено
картинки по всем признакам похожи на "паразитный" контент

**Comment by slaFFik** [comment]
а вот сейчас обидно было :) Я старался, галерею картинок создавал, а ты ее с плеча "паразитным контентом" ))
